name: tinysplat
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - numpy
  - python
  - pytorch
  - pillow
  - pip
  - matplotlib
  - imageio
  - requests
  - pyyaml
  - ipykernel
  - git+https://github.com/tinygrad/tinygrad.git
  - scipy
