defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

share_url: true
paths:
  images_path: "/Users/sebastiancavada/Documents/scsv/tinysplat/assets/Truck/images"
  json_path: "/Users/sebastiancavada/Documents/scsv/tinysplat/assets/Truck/transforms.json"
  ply_path: "/Users/sebastiancavada/Documents/scsv/tinysplat/assets/Truck/sparse_pc.ply"
